.\" -*- mode: troff; coding: UTF-8 -*-
.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" %%%LICENSE_START(VERBATIM)
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" %%%LICENSE_END
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified 1993-04-12, David Metcalfe
.\" Modified 1993-07-24, Rik Faith (faith@cs.unc.edu)
.\" Modified 2002-01-20, Walter Harms
.\"*******************************************************************
.\"
.\" This file was generated with po4a. Translate the source file.
.\"
.\"*******************************************************************
.TH BSTRING 3 2019\-03\-06 "" "Руководство программиста Linux"
.SH ИМЯ
bcmp, bcopy, bzero, memccpy, memchr, memcmp, memcpy, memfrob, memmem,
memmove, memset \- операции над байтовыми строками
.SH ОБЗОР
.nf
\fB#include <string.h>\fP
.PP
\fBint bcmp(const void *\fP\fIs1\fP\fB, const void *\fP\fIs2\fP\fB, size_t \fP\fIn\fP\fB);\fP
.PP
\fBvoid bcopy(const void *\fP\fIsrc\fP\fB, void *\fP\fIdest\fP\fB, size_t \fP\fIn\fP\fB);\fP
.PP
\fBvoid bzero(void *\fP\fIs\fP\fB, size_t \fP\fIn\fP\fB);\fP
.PP
\fBvoid *memccpy(void *\fP\fIdest\fP\fB, const void *\fP\fIsrc\fP\fB, int \fP\fIc\fP\fB, size_t \fP\fIn\fP\fB);\fP
.PP
\fBvoid *memchr(const void *\fP\fIs\fP\fB, int \fP\fIc\fP\fB, size_t \fP\fIn\fP\fB);\fP
.PP
\fBint memcmp(const void *\fP\fIs1\fP\fB, const void *\fP\fIs2\fP\fB, size_t \fP\fIn\fP\fB);\fP
.PP
\fBvoid *memcpy(void *\fP\fIdest\fP\fB, const void *\fP\fIsrc\fP\fB, size_t \fP\fIn\fP\fB);\fP
.PP
\fBvoid *memfrob(void *\fP\fIs\fP\fB, size_t \fP\fIn\fP\fB);\fP
.PP
\fBvoid *memmem(const void *\fP\fIhaystack\fP\fB, size_t \fP\fIhaystacklen\fP\fB,\fP
\fB             const void *\fP\fIneedle\fP\fB, size_t \fP\fIneedlelen\fP\fB);\fP
.PP
\fBvoid *memmove(void *\fP\fIdest\fP\fB, const void *\fP\fIsrc\fP\fB, size_t \fP\fIn\fP\fB);\fP
.PP
\fBvoid *memset(void *\fP\fIs\fP\fB, int \fP\fIc\fP\fB, size_t \fP\fIn\fP\fB);\fP
.fi
.SH ОПИСАНИЕ
Эти функции производят операции над строками (массивами байтов), которые
могут не заканчиваться null. Смотрите конкретные справочные страницы с
описаниями каждой функции.
.SH ЗАМЕЧАНИЯ
.\" The old functions are not even available on some non-GNU/Linux systems.
Функции \fBbcmp\fP(), \fBbcopy\fP() и \fBbzero\fP() являются устаревшими. Вместо них
используйте \fBmemcmp\fP(), \fBmemcpy\fP() и \fBmemset\fP().
.SH "СМОТРИТЕ ТАКЖЕ"
\fBbcmp\fP(3), \fBbcopy\fP(3), \fBbzero\fP(3), \fBmemccpy\fP(3), \fBmemchr\fP(3),
\fBmemcmp\fP(3), \fBmemcpy\fP(3), \fBmemfrob\fP(3), \fBmemmem\fP(3), \fBmemmove\fP(3),
\fBmemset\fP(3)
