.\" -*- mode: troff; coding: UTF-8 -*-
.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" %%%LICENSE_START(VERBATIM)
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" %%%LICENSE_END
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sun Jul 25 10:41:28 1993 by Rik Faith (faith@cs.unc.edu)
.\"*******************************************************************
.\"
.\" This file was generated with po4a. Translate the source file.
.\"
.\"*******************************************************************
.TH STRXFRM 3 2019\-03\-06 GNU "Руководство программиста Linux"
.SH ИМЯ
strxfrm \- преобразование строки
.SH ОБЗОР
.nf
\fB#include <string.h>\fP
.PP
\fBsize_t strxfrm(char *\fP\fIdest\fP\fB, const char *\fP\fIsrc\fP\fB, size_t \fP\fIn\fP\fB);\fP
.fi
.SH ОПИСАНИЕ
Функция \fBstrxfrm\fP() преобразует строку \fIsrc\fP в такую форму, что выполнение
\fBstrcmp\fP(3) над двумя такими строками, преобразованными посредством
\fBstrxfrm\fP(), будет таким же, как и выполнение \fBstrcoll\fP(3) над строками до
преобразования. Первые \fIn\fP байт преобразованной строки помещаются в
\fIdest\fP. Преобразование основывается на настройках категории текущей локали
\fBLC_COLLATE\fP программы (смотрите \fBsetlocale\fP(3)).
.SH "ВОЗВРАЩАЕМОЕ ЗНАЧЕНИЕ"
Функция \fBstrxfrm\fP() возвращает количество байт, необходимое для размещения
преобразованной строки в \fIdest\fP без завершающего байта null («\e0»). Если
возвращённое значение равно \fIn\fP или больше этой величины, то содержимое
\fIdest\fP не определено.
.SH АТРИБУТЫ
Описание терминов данного раздела смотрите в \fBattributes\fP(7).
.TS
allbox;
lb lb lb
l l l.
Интерфейс	Атрибут	Значение
T{
\fBstrxfrm\fP()
T}	Безвредность в нитях	MT\-Safe locale
.TE
.SH "СООТВЕТСТВИЕ СТАНДАРТАМ"
POSIX.1\-2001, POSIX.1\-2008, C89, C99, SVr4, 4.3BSD.
.SH "СМОТРИТЕ ТАКЖЕ"
\fBbcmp\fP(3), \fBmemcmp\fP(3), \fBsetlocale\fP(3), \fBstrcasecmp\fP(3), \fBstrcmp\fP(3),
\fBstrcoll\fP(3), \fBstring\fP(3)
